name: Android CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Clone submodules
      run: git submodule update --init --recursive
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test app with Gradle
      run: ./gradlew app:testDebug
    - name: Build debug APK with Gradle
      run: ./gradlew app:packageDebug
    - name: Upload debug APK artifact
      uses: actions/upload-artifact@v3.1.1
      with:
         name: Openboard
         path: ./app/build/outputs/apk/debug/*.apk
