name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload our APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload lint report
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Lint report
          path: app/build/reports/lint-results-debug.html
